import type { Metadata } from "next";
import { Public_Sans, Heebo,  } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Nav";
import WhatsAppButton from "./components/WhatsAppButton";
const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

const heebo = Heebo({
  variable: "--font-heebo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Óptica Real",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        {/* Script do LightWidget para carregar o feed do Instagram */}
        <script
          src="https://cdn.lightwidget.com/widgets/lightwidget.js"
          async
        ></script>
      </head>
      <body
        className={`${publicSans.variable} ${heebo.variable} antialiased`}
      >
        <Navbar />
        <div>
          {children}
          <WhatsAppButton />
        </div>
        <Footer />
      </body>
    </html>
  );
}
